spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jpa_basic?serverTimezone=Asia/Seoul
    username: jae
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true